import { StyleSheet } from 'react-native';

import { tokens } from '@/constants/tokens';

const colors = tokens.colors.semantic.light;
const { radius, spacing } = tokens;

/** Styles for the profile feature's review lists, cards, forms, and feedback. */
export const reviewStyles = StyleSheet.create({
  reviewCountLabel: {
    color: '#333D4B',
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    height: 24,
    letterSpacing: -0.32,
    lineHeight: 24,
    marginTop: spacing[20],
  },
  reviewCountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 24,
    marginTop: spacing[20],
  },
  viewAllLink: {
    color: colors.primary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 13,
    fontWeight: '600',
  },
  reviewPreviewScroll: {
    marginHorizontal: -spacing[20],
    marginTop: spacing[8],
    overflow: 'visible',
  },
  reviewPreviewContent: {
    paddingHorizontal: spacing[20],
    paddingVertical: spacing[4],
  },
  reviewPreviewCard: { marginRight: spacing[12] },
  reviewList: { gap: spacing[16], marginTop: spacing[16] },
  reviewCard: {
    backgroundColor: colors.surface,
    borderColor: '#F2F4F6',
    borderRadius: radius[16],
    borderWidth: 1,
    gap: spacing[16],
    paddingBottom: spacing[16],
    paddingHorizontal: spacing[16],
    paddingTop: spacing[24],
    shadowColor: '#000000',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  reviewCardCopy: { gap: spacing[8] },
  reviewCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    justifyContent: 'space-between',
  },
  reviewPlaceName: {
    color: '#333D4B',
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.32,
    lineHeight: 24,
  },
  reviewMenuButton: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  reviewRatingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
  },
  starButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  editableStar: { color: '#FFB800', fontSize: 30, lineHeight: 34 },
  readonlyStars: { height: 12, width: 70.604 },
  reviewRatingMetaRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing[8], height: 20 },
  reviewRatingText: {
    color: '#333D4B',
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
  reviewMeta: {
    color: '#B0B8C1',
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
  reviewDogChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#E5E8EB',
    borderRadius: radius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing[4],
    overflow: 'hidden',
    paddingBottom: spacing[4],
    paddingLeft: spacing[4],
    paddingRight: spacing[12],
    paddingTop: spacing[4],
  },
  reviewDogAvatar: {
    alignItems: 'center',
    backgroundColor: '#CED4DA',
    borderRadius: radius.full,
    height: 24,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 24,
  },
  reviewDogAvatarImage: { height: '100%', width: '100%' },
  reviewDogName: {
    color: '#333D4B',
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
  reviewContent: {
    color: '#333D4B',
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: -0.28,
    lineHeight: 22,
    minHeight: 44,
  },
  reviewPhotos: { gap: spacing[8] },
  reviewPhoto: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 105,
    width: 140,
  },
  photoPickerRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[8] },
  photoThumbWrap: { position: 'relative' },
  photoThumb: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 88,
    width: 88,
  },
  photoRemoveBadge: {
    alignItems: 'center',
    backgroundColor: colors.overlayScrim,
    borderRadius: radius.full,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[4],
    top: spacing[4],
    width: 20,
  },
  addPhotoButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[8],
    borderStyle: 'dashed',
    borderWidth: 1,
    height: 88,
    justifyContent: 'center',
    width: 88,
  },
  addPhotoLabel: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 11,
    marginTop: spacing[4],
  },
  ratingField: { alignItems: 'center', gap: spacing[8] },
  emptyReviewCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius[16],
    borderWidth: 1,
    gap: 28,
    height: 180,
    justifyContent: 'center',
    marginTop: spacing[12],
    paddingHorizontal: spacing[20],
    paddingVertical: spacing[40],
    width: '100%',
  },
  emptyReviewCopy: { gap: spacing[4], width: 248 },
  emptyReviewDescription: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 13,
    height: 20,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyReviewIcon: { height: 24, width: 24 },
  emptyReviewTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    height: 24,
    lineHeight: 24,
    textAlign: 'center',
  },
  visitedSection: { gap: spacing[8], marginTop: spacing[24] },
  visitedRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[10],
    justifyContent: 'space-between',
    minHeight: 52,
  },
  visitedThumbnail: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 44,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 44,
  },
  visitedThumbnailImage: { height: '100%', width: '100%' },
  visitedBody: { flex: 1, gap: spacing[2] },
  visitedPlaceName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '600',
  },
  visitedDate: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
  },
  writeReviewButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[8],
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: spacing[10],
  },
  writeReviewButtonText: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 11,
    fontWeight: '600',
  },
  toast: {
    alignItems: 'flex-start',
    backgroundColor: colors.foreground,
    borderRadius: 20,
    bottom: 0,
    justifyContent: 'center',
    height: 52,
    left: spacing[8],
    paddingHorizontal: spacing[24],
    position: 'absolute',
    right: spacing[8],
  },
  toastText: {
    color: colors.surface,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
});
