import { StyleSheet } from 'react-native';

import { tokens } from '@/constants/tokens';

const colors = tokens.colors.semantic.light;
const { borderWidth, radius, spacing } = tokens;

export const styles = StyleSheet.create({
  root: { backgroundColor: colors.background, flex: 1 },
  content: { paddingHorizontal: spacing[20], paddingBottom: spacing[40] },
  profileTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.48,
    lineHeight: 32,
    paddingTop: spacing[16],
  },
  profileCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[12],
    height: 56,
    marginBottom: spacing[16],
    marginTop: spacing[20],
  },
  profileImage: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 56,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 56,
  },
  profileImageContent: { borderRadius: radius.full, height: '100%', width: '100%' },
  profileDefaultIcon: { height: 40, width: 40 },
  profileBody: { flex: 1, gap: spacing[4] },
  profileName: { color: colors.textPrimary, fontFamily: tokens.fonts.sansSerif, fontSize: 16, fontWeight: '700', letterSpacing: -0.32, lineHeight: 24 },
  profileMeta: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
  section: { gap: 0, marginTop: spacing[20] },
  dogSection: {},
  dogListCard: {
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: 1,
    overflow: 'hidden',
  },
  dogCard: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[12],
    height: 56,
    paddingLeft: 14,
    paddingRight: spacing[12],
  },
  dogImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 36,
    width: 36,
  },
  dogImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  dogBody: { flex: 1 },
  dogName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.28,
    lineHeight: 20,
  },
  dogMeta: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: -0.36,
    lineHeight: 16,
  },
  menuCard: {
    overflow: 'hidden',
  },
  menuRow: {
    alignItems: 'center',
    borderBottomColor: colors.surfaceSubtle,
    borderBottomWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[6],
    height: 48,
  },
  menuIcon: { height: 20, width: 20 },
  menuChevron: { height: 20, width: 20 },
  menuRowLast: { borderBottomWidth: 0 },
  menuText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: -0.32,
    lineHeight: 24,
  },
  nameChangeButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[4],
    borderWidth: 1,
    justifyContent: 'center',
    height: 28,
    paddingHorizontal: spacing[8],
  },
  nameChangeText: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: -0.33,
    lineHeight: 16.5,
  },
  loginBanner: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing[12],
    minHeight: 76,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[12],
  },
  loginBannerBody: { flex: 1, gap: spacing[2] },
  loginBannerTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 14,
  },
  loginBannerSubtitle: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 11,
    lineHeight: 16,
  },
  loggedOutMenuSection: { marginTop: spacing[20] },
  addDogButton: { alignItems: 'center', height: 48, justifyContent: 'center' },
  addDogText: {
    color: colors.primary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 14,
    fontWeight: '700',
  },
  bottomLinks: {
    flexDirection: 'row',
    gap: spacing[16],
    height: 40,
    paddingVertical: spacing[12],
  },
  bottomLinkText: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: '500',
  },
  withdrawButton: {
    alignItems: 'center',
    marginTop: spacing[24],
    paddingVertical: spacing[12],
  },
  detailImageWrap: { alignItems: 'center', paddingVertical: spacing[24] },
  detailImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 100,
    width: 100,
  },
  avatarEditWrap: { position: 'relative' },
  avatarEditBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: 2,
    bottom: 0,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 28,
  },
  avatarUploadOverlay: {
    alignItems: 'center',
    backgroundColor: colors.overlayScrim,
    borderRadius: radius.full,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  infoList: { gap: spacing[4] },
  infoRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 48,
  },
  infoLabel: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 13,
    width: 92,
  },
  infoValue: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 14,
    textAlign: 'right',
  },
  form: { gap: spacing[20], paddingVertical: spacing[20] },
  fieldLabel: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 14,
    marginBottom: spacing[8],
  },
  actions: { gap: spacing[10], marginTop: spacing[24] },
  dangerText: {
    color: '#D92D20',
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  headerDeleteButton: {
    justifyContent: 'center',
    minHeight: 40,
    paddingLeft: spacing[12],
  },
  headerDeleteText: {
    color: colors.primary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: '500',
  },
  agreementStatus: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 12,
  },
  modalOverlay: {
    backgroundColor: colors.overlayScrim,
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[24],
    borderTopRightRadius: radius[24],
    gap: spacing[16],
    padding: spacing[20],
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 18,
  },
});
