import { StyleSheet } from 'react-native';

import { tokens } from '@/constants/tokens';

const colors = tokens.colors.semantic.light;
const { radius, spacing } = tokens;

export const styles = StyleSheet.create({
  root: { backgroundColor: colors.background, flex: 1 },
  content: { padding: spacing[20], paddingBottom: spacing[40] },
  profileCard: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing[16],
    paddingVertical: spacing[24],
  },
  profileImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 72,
    width: 72,
  },
  profileImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  profileBody: { flex: 1, gap: spacing[4] },
  profileName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 18,
  },
  profileMeta: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 13,
  },
  section: { gap: spacing[12], marginTop: spacing[24] },
  reviewCountLabel: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 14,
    marginTop: spacing[20],
  },
  reviewCountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing[20],
  },
  viewAllLink: {
    color: colors.primary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 13,
  },
  reviewPreviewScroll: { marginTop: spacing[12] },
  reviewPreviewCard: { marginRight: spacing[12], width: 280 },
  dogCard: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing[12],
    padding: spacing[16],
  },
  dogImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 56,
    width: 56,
  },
  dogImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  dogBody: { flex: 1, gap: spacing[4] },
  dogName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 15,
  },
  dogMeta: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 13,
  },
  menuCard: {
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: 1,
    overflow: 'hidden',
  },
  menuRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing[12],
    minHeight: 54,
    paddingHorizontal: spacing[16],
  },
  menuRowLast: { borderBottomWidth: 0 },
  menuText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 14,
  },
  nameChangeButton: { marginLeft: spacing[8] },
  loginBanner: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius[12],
    flexDirection: 'row',
    gap: spacing[12],
    padding: spacing[16],
  },
  loginBannerBody: { flex: 1, gap: spacing[2] },
  loginBannerTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 15,
  },
  loginBannerSubtitle: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
  },
  addDogButton: { marginTop: spacing[4] },
  bottomLinks: {
    flexDirection: 'row',
    gap: spacing[16],
    justifyContent: 'center',
    marginTop: spacing[16],
  },
  bottomLinkText: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: '500',
  },
  detailImageWrap: { alignItems: 'center', paddingVertical: spacing[24] },
  detailImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 112,
    width: 112,
  },
  avatarEditWrap: { position: 'relative' },
  avatarEditBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: 2,
    bottom: 0,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 28,
  },
  avatarUploadOverlay: {
    alignItems: 'center',
    backgroundColor: colors.overlayScrim,
    borderRadius: radius.full,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  infoList: { gap: spacing[4] },
  infoRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 48,
  },
  infoLabel: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 13,
    width: 92,
  },
  infoValue: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 14,
    textAlign: 'right',
  },
  form: { gap: spacing[20], paddingVertical: spacing[20] },
  fieldLabel: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 14,
    marginBottom: spacing[8],
  },
  actions: { gap: spacing[10], marginTop: spacing[24] },
  dangerText: {
    color: '#D92D20',
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  agreementStatus: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '500',
    fontSize: 12,
  },
  modalOverlay: {
    backgroundColor: colors.overlayScrim,
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[24],
    borderTopRightRadius: radius[24],
    gap: spacing[16],
    padding: spacing[20],
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 18,
  },
  reviewCard: {
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: 1,
    gap: spacing[8],
    padding: spacing[16],
  },
  reviewCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reviewPlaceName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 15,
  },
  reviewRatingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
  },
  reviewRatingText: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '700',
    fontSize: 13,
  },
  reviewMeta: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
  },
  reviewContent: {
    color: colors.textSecondary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 13,
    lineHeight: 19,
  },
  visitedSection: { gap: spacing[10], marginTop: spacing[24] },
  visitedRow: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing[12],
    justifyContent: 'space-between',
    padding: spacing[16],
  },
  visitedBody: { gap: spacing[2] },
  visitedPlaceName: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 14,
  },
  visitedDate: {
    color: colors.textTertiary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
  },
  toast: {
    alignSelf: 'center',
    backgroundColor: colors.foreground,
    borderRadius: radius[12],
    bottom: 0,
    paddingHorizontal: spacing[20],
    paddingVertical: spacing[12],
    position: 'absolute',
  },
  toastText: {
    color: colors.surface,
    fontFamily: tokens.fonts.sansSerif,
    fontWeight: '600',
    fontSize: 13,
  },
});
