import { StyleSheet } from 'react-native';

import { tokens } from '@/constants/tokens';

export const colors = tokens.colors.semantic.light;
const { borderWidth, radius, spacing } = tokens;

const text = (
  fontSize: keyof typeof tokens.typography.fontSize,
  fontWeight: keyof typeof tokens.typography.fontWeight = 'medium',
  color: keyof typeof colors = 'textPrimary',
  lineHeight?: number,
) => ({
  color: colors[color],
  fontFamily: tokens.fonts.sansSerif,
  fontSize: tokens.typography.fontSize[fontSize].fontSize,
  fontWeight: tokens.typography.fontWeight[fontWeight],
  letterSpacing: 0,
  lineHeight: lineHeight ?? tokens.typography.fontSize[fontSize].fontSize,
});

export const styles = StyleSheet.create({
  root: {
    backgroundColor: colors.background,
    flex: 1,
    overflow: 'hidden',
  },
  homeContent: {
    flex: 1,
  },
  // 검색을 열어도 네이티브 지도와 마커 오버레이를 unmount하지 않는다.
  // 검색 결과 선택 후 복귀할 때 Fabric mount 작업이 겹치는 것을 방지한다.
  homeContentHidden: {
    flex: 1,
    opacity: 0,
  },
  searchOverlay: {
    backgroundColor: colors.background,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 30,
  },
  headerBar: {
    backgroundColor: colors.surface,
    paddingBottom: spacing[12],
    zIndex: 20,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
  },
  topControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    paddingHorizontal: spacing[16],
  },
  homePurpose: {
    color: colors.textPrimary,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 20,
    fontWeight: tokens.typography.fontWeight.bold,
    lineHeight: 28,
    marginBottom: spacing[12],
    paddingHorizontal: spacing[16],
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 44,
    paddingHorizontal: spacing[12],
  },
  searchPlaceholder: text(12, 'medium', 'textPlaceholder'),
  clearSearchButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    marginLeft: 'auto',
    width: 32,
  },
  infoButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  categoryRail: {
    height: 44,
    marginTop: spacing[12],
  },
  categoryRailContent: {
    alignItems: 'center',
    paddingLeft: spacing[16],
    paddingRight: spacing[16],
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    minHeight: 44,
    justifyContent: 'center',
    marginRight: spacing[8],
    paddingHorizontal: spacing[12],
  },
  categoryChipActive: {
    backgroundColor: colors.inverse,
    borderColor: colors.inverse,
  },
  categoryChipText: text(12, 'semibold', 'textSecondary'),
  categoryChipTextActive: text(12, 'bold', 'onInverse'),
  mapLayer: {
    backgroundColor: '#f6f2eb',
    flex: 1,
  },
  zoomControl: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: borderWidth[1],
    overflow: 'hidden',
    position: 'absolute',
    right: spacing[16],
    width: 44,
    zIndex: 16,
  },
  zoomButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  zoomDivider: {
    backgroundColor: colors.border,
    height: borderWidth[1],
    width: '100%',
  },
  mapBottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[16],
    borderTopRightRadius: radius[16],
    left: 0,
    bottom: 0,
    paddingHorizontal: spacing[16],
    paddingTop: spacing[8],
    position: 'absolute',
    right: 0,
    zIndex: 15,
  },
  mapFloatingAction: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 44,
    justifyContent: 'center',
    minWidth: 124,
    paddingHorizontal: spacing[12],
    position: 'absolute',
    zIndex: 18,
  },
  mapFloatingActionText: text(12, 'semibold', 'textSecondary'),
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 4,
    width: 42,
  },
  sheetDragArea: {
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  placeListCount: {
    ...text(12, 'medium', 'textTertiary'),
    marginBottom: spacing[8],
  },
  placePreviewWrapper: {
    left: spacing[16],
    position: 'absolute',
    right: spacing[16],
    zIndex: 19,
  },
  placePreviewCard: {
    backgroundColor: colors.surface,
    borderRadius: radius[16],
    padding: spacing[12],
    shadowColor: '#111827',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 6,
  },
  placePreviewCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    shadowColor: '#111827',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 6,
    top: -52,
    width: 44,
  },
  listWrapper: {
    flex: 1,
  },
  emptyList: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing[16],
    paddingVertical: spacing[16],
  },
  emptyListTitle: text(14, 'bold', 'textSecondary'),
  emptyListText: {
    ...text(12, 'medium', 'textTertiary'),
    marginTop: spacing[8],
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    minHeight: 44,
    justifyContent: 'center',
    marginTop: spacing[16],
    paddingHorizontal: spacing[16],
    paddingVertical: spacing[8],
  },
  retryButtonText: text(12, 'semibold', 'textSecondary'),
  placeRow: {
    borderColor: 'transparent',
    borderRadius: radius[12],
    borderWidth: borderWidth[2],
    flexDirection: 'row',
    gap: spacing[10],
    minHeight: 116,
    marginBottom: spacing[4],
    padding: spacing[8],
  },
  placeRowCompact: {
    marginBottom: 0,
    minHeight: 104,
  },
  placeRowImageFrame: {
    borderRadius: radius[8],
    height: 92,
    position: 'relative',
    width: 92,
  },
  placeRowImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 92,
    width: 92,
  },
  placeRowBody: {
    flex: 1,
  },
  placeRowHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    justifyContent: 'space-between',
  },
  placeRowTitle: {
    ...text(14, 'bold', 'textPrimary'),
    flex: 1,
  },
  placeCategoryText: {
    ...text(11, 'semibold', 'textTertiary'),
    marginTop: spacing[4],
  },
  placeTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
    marginTop: spacing[6],
  },
  placeTagChip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius[4],
    minHeight: 24,
    justifyContent: 'center',
    paddingHorizontal: spacing[6],
  },
  placeTagText: text(11, 'bold', 'textTertiary'),
  placeAddressRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: spacing[8],
  },
  placeAddressText: {
    ...text(11, 'medium', 'textPlaceholder'),
    flex: 1,
  },
  listBottomSpacer: {
    height: 64,
  },
  mapSwitchButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    bottom: spacing[16],
    flexDirection: 'row',
    gap: spacing[6],
    height: 38,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: spacing[12],
    position: 'absolute',
  },
  mapSwitchText: text(12, 'semibold', 'textSecondary'),
  searchRoot: {
    backgroundColor: colors.background,
    flex: 1,
    paddingHorizontal: spacing[16],
  },
  searchHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
  },
  backButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 44,
    paddingHorizontal: spacing[12],
  },
  searchTextInput: {
    color: colors.textPrimary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: tokens.typography.fontWeight.medium,
    height: 44,
    letterSpacing: 0,
    padding: 0,
  },
  searchSection: {
    marginTop: spacing[24],
  },
  searchSectionTitle: {
    ...text(14, 'bold', 'textPrimary'),
    marginBottom: spacing[12],
  },
  suggestionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[10],
    minHeight: 44,
  },
  suggestionText: text(14, 'medium', 'textSecondary'),
  suggestionHighlightText: text(14, 'bold', 'primary'),
  imagePlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    justifyContent: 'center',
  },
});
