import { StyleSheet } from 'react-native';

import { tokens } from '@/constants/tokens';

export const colors = tokens.colors.semantic.light;
const { borderWidth, radius, spacing } = tokens;

const text = (
  fontSize: keyof typeof tokens.typography.fontSize,
  fontWeight: keyof typeof tokens.typography.fontWeight = 'medium',
  color: keyof typeof colors = 'textPrimary',
  lineHeight?: number,
) => ({
  color: colors[color],
  fontFamily: tokens.fonts.sansSerif,
  fontSize: tokens.typography.fontSize[fontSize].fontSize,
  fontWeight: tokens.typography.fontWeight[fontWeight],
  letterSpacing: 0,
  lineHeight: lineHeight ?? tokens.typography.fontSize[fontSize].fontSize,
});

export const styles = StyleSheet.create({
  root: {
    backgroundColor: colors.background,
    flex: 1,
    overflow: 'hidden',
  },
  headerBar: {
    backgroundColor: colors.surface,
    paddingBottom: spacing[8],
    zIndex: 20,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
  },
  topControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    paddingHorizontal: spacing[16],
  },
  dogSelector: {
    alignItems: 'center',
    backgroundColor: colors.inverse,
    borderRadius: radius.full,
    flexDirection: 'row',
    gap: spacing[4],
    height: 36,
    paddingLeft: spacing[4],
    paddingRight: spacing[8],
  },
  dogAvatarStack: {
    alignItems: 'center',
    flexDirection: 'row',
    minWidth: 28,
  },
  stackedDogAvatar: {
    borderColor: colors.inverse,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 28,
    width: 28,
  },
  dogSelectorText: text(12, 'bold', 'onInverse'),
  dogSelectorEmpty: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 36,
    paddingHorizontal: spacing[12],
  },
  dogSelectorAddText: text(12, 'bold', 'primary'),
  searchButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 36,
    paddingHorizontal: spacing[12],
  },
  searchPlaceholder: text(12, 'medium', 'textPlaceholder'),
  categoryRail: {
    height: 34,
    marginTop: spacing[12],
  },
  categoryRailContent: {
    paddingLeft: spacing[16],
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 34,
    justifyContent: 'center',
    marginRight: spacing[8],
    paddingHorizontal: spacing[12],
  },
  categoryChipActive: {
    backgroundColor: colors.inverse,
    borderColor: colors.inverse,
  },
  categoryChipText: text(12, 'semibold', 'textSecondary'),
  categoryChipTextActive: text(12, 'bold', 'onInverse'),
  mapLayer: {
    backgroundColor: '#f6f2eb',
    flex: 1,
  },
  placeMarkerBubble: {
    alignItems: 'center',
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 34,
    justifyContent: 'center',
    shadowColor: '#111827',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    width: 34,
  },
  placeMarkerBubbleDimmed: {
    borderColor: 'rgba(148, 163, 184, 0.45)',
    opacity: 0.5,
    transform: [{ scale: 0.88 }],
  },
  placeMarkerBubbleHighlighted: {
    borderColor: colors.surface,
    borderWidth: borderWidth[2],
    opacity: 1,
    transform: [{ scale: 1.12 }],
  },
  placeMarkerSymbol: {
    height: 17,
    width: 17,
  },
  nativeUserLocationMarker: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 38,
    width: 38,
  },
  myLocationButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[16],
    width: 44,
    zIndex: 16,
  },
  zoomControl: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: borderWidth[1],
    overflow: 'hidden',
    position: 'absolute',
    right: spacing[16],
    width: 44,
    zIndex: 16,
  },
  zoomButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  zoomDivider: {
    backgroundColor: colors.border,
    height: borderWidth[1],
    width: '100%',
  },
  mapBottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[16],
    borderTopRightRadius: radius[16],
    left: 0,
    paddingHorizontal: spacing[16],
    paddingTop: spacing[8],
    position: 'absolute',
    right: 0,
    zIndex: 15,
  },
  mapSheetFeedScroll: {
    flex: 1,
  },
  mapSheetFeedContent: {
    paddingBottom: 32,
  },
  mapFloatingAction: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 34,
    justifyContent: 'center',
    minWidth: 124,
    paddingHorizontal: spacing[12],
    position: 'absolute',
    zIndex: 18,
  },
  mapFloatingActionText: text(12, 'semibold', 'textSecondary'),
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 4,
    width: 42,
  },
  sheetDragArea: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  sheetLoadingRow: {
    alignItems: 'center',
    marginBottom: spacing[8],
  },
  placeListCount: {
    ...text(12, 'bold', 'textSecondary'),
    marginBottom: spacing[8],
  },
  horizontalCardRail: {
    marginLeft: -spacing[2],
  },
  listWrapper: {
    flex: 1,
  },
  emptyList: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    paddingHorizontal: spacing[16],
    paddingVertical: spacing[24],
  },
  emptyListTitle: text(14, 'bold', 'textSecondary'),
  emptyListText: {
    ...text(12, 'medium', 'textTertiary'),
    marginTop: spacing[8],
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 38,
    justifyContent: 'center',
    marginTop: spacing[16],
    paddingHorizontal: spacing[16],
  },
  retryButtonText: text(12, 'semibold', 'textSecondary'),
  placeRow: {
    flexDirection: 'row',
    gap: spacing[10],
    minHeight: 116,
    paddingBottom: spacing[12],
  },
  placeRowCompact: {
    minHeight: 104,
  },
  placeRowImageFrame: {
    borderRadius: radius[8],
    height: 92,
    position: 'relative',
    width: 92,
  },
  placeRowImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 92,
    width: 92,
  },
  placeLikeBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[6],
    top: spacing[6],
    width: 30,
  },
  compatibleDogStack: {
    alignItems: 'center',
    bottom: -spacing[6],
    flexDirection: 'row',
    left: spacing[6],
    position: 'absolute',
  },
  compatibleDogAvatar: {
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 28,
    width: 28,
  },
  placeRowBody: {
    flex: 1,
  },
  placeRowHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    justifyContent: 'space-between',
  },
  placeRowTitle: {
    ...text(14, 'bold', 'textPrimary'),
    flex: 1,
  },
  addTripButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[4],
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 28,
    justifyContent: 'center',
    minWidth: 74,
    paddingHorizontal: spacing[8],
  },
  addTripText: text(11, 'bold', 'textSecondary'),
  placeTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
    marginTop: spacing[6],
  },
  placeTagChip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius[4],
    minHeight: 24,
    justifyContent: 'center',
    paddingHorizontal: spacing[6],
  },
  placeTagText: text(11, 'bold', 'textTertiary'),
  placeProofRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[8],
    marginTop: spacing[8],
  },
  placeOfficialBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
  },
  placeOfficialText: text(11, 'bold', 'accentBlue'),
  placeUserProof: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing[4],
    minWidth: 104,
  },
  placeUserProofText: {
    ...text(11, 'semibold', 'textPlaceholder'),
    flex: 1,
  },
  placeRatingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
    marginTop: spacing[4],
  },
  placeRatingText: text(11, 'semibold', 'textTertiary'),
  placeAddressText: {
    ...text(11, 'medium', 'textPlaceholder'),
    flex: 1,
    marginLeft: spacing[4],
  },
  listBottomSpacer: {
    height: 64,
  },
  mapSwitchButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    bottom: spacing[16],
    flexDirection: 'row',
    gap: spacing[6],
    height: 38,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: spacing[12],
    position: 'absolute',
  },
  mapSwitchText: text(12, 'semibold', 'textSecondary'),
  modalBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDismissArea: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  dogSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[24],
    borderTopRightRadius: radius[24],
    paddingHorizontal: spacing[20],
    paddingTop: spacing[20],
    zIndex: 1,
  },
  dogSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing[16],
  },
  dogSheetTitle: text(18, 'bold', 'textPrimary'),
  dogSheetCloseButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  dogOptionRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: borderWidth.hairline,
    flexDirection: 'row',
    gap: spacing[12],
    minHeight: 104,
    paddingVertical: spacing[12],
  },
  dogOptionImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 72,
    width: 72,
  },
  dogOptionBody: {
    flex: 1,
    gap: spacing[6],
  },
  dogInfoLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[12],
  },
  dogInfoLabel: {
    ...text(12, 'medium', 'textTertiary'),
    width: 32,
  },
  dogInfoValue: {
    ...text(14, 'bold', 'textPrimary'),
    flex: 1,
  },
  dogSheetActions: {
    flexDirection: 'row',
    gap: spacing[8],
    marginTop: spacing[24],
  },
  dogEditButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: borderWidth[1],
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  dogEditButtonText: text(14, 'bold', 'textSecondary'),
  dogSaveButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius[12],
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  dogSaveButtonText: text(14, 'bold', 'onPrimary'),
  placeCardRoot: {
    marginRight: spacing[10],
    width: 142,
  },
  placeCardImageFrame: {
    height: 104,
    position: 'relative',
    width: 142,
  },
  placeCardImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 104,
    width: 142,
  },
  placeCardBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 22,
    justifyContent: 'center',
    left: spacing[6],
    paddingHorizontal: spacing[8],
    position: 'absolute',
    top: spacing[6],
  },
  placeCardBadgeText: text(11, 'bold', 'onInverse'),
  placeCardLikeBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 24,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[6],
    top: spacing[6],
    width: 24,
  },
  placeCardBody: {
    paddingTop: spacing[8],
  },
  placeName: text(12, 'bold', 'textPrimary'),
  placeMeta: {
    ...text(11, 'medium', 'textTertiary'),
    marginTop: spacing[2],
  },
  placeScore: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
    marginTop: spacing[4],
  },
  scoreText: text(11, 'semibold', 'accentBlue'),
  feedSection: {
    marginBottom: spacing[24],
  },
  courseCardRoot: {
    marginRight: spacing[10],
    width: 220,
  },
  courseCardImageFrame: {
    borderRadius: radius[12],
    height: 140,
    overflow: 'hidden',
    position: 'relative',
    width: 220,
  },
  courseCardImage: {
    backgroundColor: colors.surfaceMuted,
    height: 140,
    width: 220,
  },
  courseCardBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 24,
    justifyContent: 'center',
    left: spacing[8],
    paddingHorizontal: spacing[8],
    position: 'absolute',
    top: spacing[8],
  },
  courseCardBadgeText: text(11, 'bold', 'onInverse'),
  courseCardLikeBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[8],
    top: spacing[8],
    width: 28,
  },
  courseCardOverlay: {
    backgroundColor: 'rgba(17, 24, 28, 0.42)',
    bottom: 0,
    left: 0,
    paddingHorizontal: spacing[12],
    paddingTop: spacing[20],
    paddingBottom: spacing[12],
    position: 'absolute',
    right: 0,
  },
  courseCardTitle: text(14, 'bold', 'onInverse'),
  courseCardSubtitle: {
    ...text(11, 'medium', 'onInverse'),
    marginTop: spacing[2],
    opacity: 0.85,
  },
  courseCardFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: spacing[8],
  },
  courseCardTripButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius[4],
    flexDirection: 'row',
    gap: spacing[4],
    height: 26,
    justifyContent: 'center',
    paddingHorizontal: spacing[8],
  },
  courseCardTripText: text(11, 'bold', 'textSecondary'),
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    ...text(14, 'bold', 'textPrimary'),
    marginBottom: spacing[12],
  },
  moreButton: {
    marginBottom: spacing[12],
  },
  moreText: text(11, 'semibold', 'textTertiary'),
  bottomTabs: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: borderWidth.hairline,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 30,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    gap: spacing[2],
    justifyContent: 'center',
  },
  tabLabel: text(11, 'medium', 'textTertiary'),
  tabLabelActive: text(11, 'bold', 'primary'),
  searchRoot: {
    backgroundColor: colors.background,
    flex: 1,
    paddingHorizontal: spacing[16],
  },
  searchHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
  },
  backButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 28,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 36,
    paddingHorizontal: spacing[12],
  },
  searchTextInput: {
    color: colors.textPrimary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: tokens.typography.fontWeight.medium,
    height: 36,
    letterSpacing: 0,
    padding: 0,
  },
  searchSection: {
    marginTop: spacing[24],
  },
  searchSectionTitle: {
    ...text(14, 'bold', 'textPrimary'),
    marginBottom: spacing[12],
  },
  keywordWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[8],
  },
  keywordPill: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 32,
    justifyContent: 'center',
    paddingHorizontal: spacing[12],
  },
  hotKeywordPill: {
    backgroundColor: colors.accentOrangeSubtle,
    borderColor: colors.accentOrangeMuted,
  },
  hotKeywordText: text(12, 'semibold', 'primary'),
  suggestionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[10],
    height: 40,
  },
  suggestionText: text(14, 'medium', 'textSecondary'),
  recentSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 40,
    justifyContent: 'space-between',
  },
  recentSearchButton: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing[10],
  },
  recentSearchRemoveButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
});
