import { colors, text, radius, spacing } from './style-primitives';

export const cardsStyles = {
  placeCardRoot: {
    marginRight: spacing[10],
    width: 142,
  },
  placeCardImageFrame: {
    height: 104,
    position: 'relative',
    width: 142,
  },
  placeCardImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 104,
    width: 142,
  },
  placeCardBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 22,
    justifyContent: 'center',
    left: spacing[6],
    paddingHorizontal: spacing[8],
    position: 'absolute',
    top: spacing[6],
  },
  placeCardBadgeText: text(11, 'bold', 'onInverse'),
  placeCardLikeBadge: { position: 'absolute', right: spacing[6], top: spacing[6] },
  placeCardBody: {
    paddingTop: spacing[8],
  },
  placeName: text(12, 'bold', 'textPrimary'),
  placeMeta: {
    ...text(11, 'medium', 'textTertiary'),
    marginTop: spacing[2],
  },
  placeScore: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
    marginTop: spacing[4],
  },
  scoreText: text(11, 'semibold', 'accentBlue'),
  feedSection: {
    marginBottom: spacing[24],
  },
  courseCardRoot: {
    marginRight: spacing[10],
    width: 220,
  },
  courseCardImageFrame: {
    borderRadius: radius[12],
    height: 140,
    overflow: 'hidden',
    position: 'relative',
    width: 220,
  },
  courseCardImage: {
    backgroundColor: colors.surfaceMuted,
    height: 140,
    width: 220,
  },
  courseCardBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderRadius: radius.full,
    height: 24,
    justifyContent: 'center',
    left: spacing[8],
    paddingHorizontal: spacing[8],
    position: 'absolute',
    top: spacing[8],
  },
  courseCardBadgeText: text(11, 'bold', 'onInverse'),
  courseCardLikeBadge: { position: 'absolute', right: spacing[8], top: spacing[8] },
  courseCardOverlay: {
    backgroundColor: 'rgba(17, 24, 28, 0.42)',
    bottom: 0,
    left: 0,
    paddingHorizontal: spacing[12],
    paddingTop: spacing[20],
    paddingBottom: spacing[12],
    position: 'absolute',
    right: 0,
  },
  courseCardTitle: text(14, 'bold', 'onInverse'),
  courseCardSubtitle: {
    ...text(11, 'medium', 'onInverse'),
    marginTop: spacing[2],
    opacity: 0.85,
  },
  courseCardFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: spacing[8],
  },
  courseCardTripButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius[4],
    flexDirection: 'row',
    gap: spacing[4],
    height: 26,
    justifyContent: 'center',
    paddingHorizontal: spacing[8],
  },
  courseCardTripText: text(11, 'bold', 'textSecondary'),
} as const;
