import { colors, text, radius, borderWidth, shadow, spacing } from './style-primitives';

const PLACE_ROW_IMAGE_SIZE = 88;
const LIKE_BADGE_SIZE = 24;

export const listStyles = {
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 4,
    width: 42,
  },
  sheetDragArea: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  sheetLoadingRow: {
    alignItems: 'center',
    marginBottom: spacing[8],
  },
  placeListCount: {
    ...text(12, 'bold', 'textSecondary'),
    marginBottom: spacing[8],
  },
  placePreviewWrapper: {
    left: spacing[16],
    position: 'absolute',
    right: spacing[16],
    zIndex: 19,
  },
  placePreviewCard: {
    backgroundColor: colors.surface,
    borderRadius: radius[16],
    padding: spacing[8],
    shadowColor: '#111827',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  placePreviewCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    height: 36,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    shadowColor: '#111827',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 6,
    top: -48,
    width: 36,
  },
  horizontalCardRail: {
    marginLeft: -spacing[2],
  },
  listWrapper: {
    flex: 1,
  },
  emptyList: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    paddingHorizontal: spacing[16],
    paddingVertical: spacing[24],
  },
  emptyListTitle: text(14, 'bold', 'textSecondary'),
  emptyListText: {
    ...text(12, 'medium', 'textTertiary'),
    marginTop: spacing[8],
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 38,
    justifyContent: 'center',
    marginTop: spacing[16],
    paddingHorizontal: spacing[16],
  },
  retryButtonText: text(12, 'semibold', 'textSecondary'),
  placeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing[12],
    paddingBottom: spacing[12],
  },
  // 프리뷰 카드는 카드 자체가 padding 8을 갖는다(Figma 310:2704, 총 높이 104).
  placeRowCompact: {
    paddingBottom: 0,
  },
  placeRowMain: {
    alignItems: 'flex-start',
    flex: 1,
    flexDirection: 'row',
    gap: spacing[12],
    minWidth: 0,
  },
  placeRowImageFrame: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[12],
    height: PLACE_ROW_IMAGE_SIZE,
    overflow: 'hidden',
    position: 'relative',
    width: PLACE_ROW_IMAGE_SIZE,
  },
  placeRowImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[12],
    height: PLACE_ROW_IMAGE_SIZE,
    width: PLACE_ROW_IMAGE_SIZE,
  },
  // 찜 버튼은 행 루트를 기준으로 썸네일 오른쪽 위에 겹친다.
  placeLikeBadge: {
    left: PLACE_ROW_IMAGE_SIZE - LIKE_BADGE_SIZE - spacing[6],
    position: 'absolute',
    top: spacing[6],
  },
  compatibleDogStack: {
    alignItems: 'center',
    bottom: spacing[6],
    flexDirection: 'row',
    left: spacing[6],
    position: 'absolute',
    ...shadow.smallOverlay,
  },
  compatibleDogAvatar: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 18,
    width: 18,
  },
  placeRowBody: {
    flex: 1,
    gap: spacing[2],
    minWidth: 0,
  },
  placeRowTitle: text(14, 'bold', 'textSecondary', 20),
  addTripButton: {
    alignItems: 'center',
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius[8],
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 28,
    justifyContent: 'center',
    paddingLeft: spacing[4],
    paddingRight: spacing[8],
  },
  addTripText: text(11, 'bold', 'textSecondary', 16.5),
  placeTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
  },
  placeTagChip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius[4],
    height: 20,
    justifyContent: 'center',
    paddingHorizontal: spacing[4],
  },
  placeTagText: text(11, 'semibold', 'textTertiary', 16.5),
  placeProofRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
  },
  placeProofIcon: { height: 16, width: 16 },
  placeOfficialBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[2],
    height: 20,
  },
  placeOfficialText: text(11, 'semibold', 'accentBlue', 16.5),
  placeUserProof: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing[2],
    height: 20,
  },
  placeUserProofText: {
    ...text(11, 'semibold', 'textPlaceholder', 16.5),
    flex: 1,
  },
  placeUserProofRelative: text(11, 'regular', 'textDisabled', 16.5),
  placeRatingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[2],
  },
  placeStarIcon: { height: 8, width: 8 },
  placeRatingText: text(10, 'medium', 'textTertiary', 12),
  placeAddressText: {
    ...text(11, 'medium', 'textPlaceholder', 16.5),
    flex: 1,
    marginLeft: spacing[4],
  },
  listBottomSpacer: {
    height: 64,
  },
  mapSwitchButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    bottom: spacing[16],
    flexDirection: 'row',
    gap: spacing[6],
    height: 38,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: spacing[12],
    position: 'absolute',
  },
  mapSwitchText: text(12, 'semibold', 'textSecondary'),
} as const;
