import { colors, text, radius, borderWidth, spacing } from './style-primitives';

export const listStyles = {
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 4,
    width: 42,
  },
  sheetDragArea: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  sheetLoadingRow: {
    alignItems: 'center',
    marginBottom: spacing[8],
  },
  placeListCount: {
    ...text(12, 'bold', 'textSecondary'),
    marginBottom: spacing[8],
  },
  placePreviewWrapper: {
    left: spacing[16],
    position: 'absolute',
    right: spacing[16],
    zIndex: 19,
  },
  placePreviewCard: {
    backgroundColor: colors.surface,
    borderRadius: radius[16],
    paddingHorizontal: spacing[16],
    paddingTop: spacing[16],
    shadowColor: '#111827',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 6,
  },
  placePreviewCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    height: 36,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    shadowColor: '#111827',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 6,
    top: -48,
    width: 36,
  },
  horizontalCardRail: {
    marginLeft: -spacing[2],
  },
  listWrapper: {
    flex: 1,
  },
  emptyList: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    paddingHorizontal: spacing[16],
    paddingVertical: spacing[24],
  },
  emptyListTitle: text(14, 'bold', 'textSecondary'),
  emptyListText: {
    ...text(12, 'medium', 'textTertiary'),
    marginTop: spacing[8],
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 38,
    justifyContent: 'center',
    marginTop: spacing[16],
    paddingHorizontal: spacing[16],
  },
  retryButtonText: text(12, 'semibold', 'textSecondary'),
  placeRow: {
    flexDirection: 'row',
    gap: spacing[10],
    minHeight: 116,
    paddingBottom: spacing[12],
  },
  placeRowCompact: {
    minHeight: 104,
  },
  placeRowImageFrame: {
    borderRadius: radius[8],
    height: 92,
    position: 'relative',
    width: 92,
  },
  placeRowImage: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius[8],
    height: 92,
    width: 92,
  },
  placeLikeBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(25, 31, 40, 0.58)',
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[6],
    top: spacing[6],
    width: 30,
  },
  compatibleDogStack: {
    alignItems: 'center',
    bottom: -spacing[6],
    flexDirection: 'row',
    left: spacing[6],
    position: 'absolute',
  },
  compatibleDogAvatar: {
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 28,
    width: 28,
  },
  placeRowBody: {
    flex: 1,
  },
  placeRowHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    justifyContent: 'space-between',
  },
  placeRowTitle: {
    ...text(14, 'bold', 'textPrimary'),
    flex: 1,
  },
  addTripButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius[4],
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 28,
    justifyContent: 'center',
    minWidth: 74,
    paddingHorizontal: spacing[8],
  },
  addTripText: text(11, 'bold', 'textSecondary'),
  placeTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
    marginTop: spacing[6],
  },
  placeTagChip: {
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius[4],
    minHeight: 24,
    justifyContent: 'center',
    paddingHorizontal: spacing[6],
  },
  placeTagText: text(11, 'bold', 'textTertiary'),
  placeProofRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[8],
    marginTop: spacing[8],
  },
  placeOfficialBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
  },
  placeOfficialText: text(11, 'bold', 'accentBlue'),
  placeUserProof: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing[4],
    minWidth: 104,
  },
  placeUserProofText: {
    ...text(11, 'semibold', 'textPlaceholder'),
    flex: 1,
  },
  placeRatingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[4],
    marginTop: spacing[4],
  },
  placeRatingText: text(11, 'semibold', 'textTertiary'),
  placeAddressText: {
    ...text(11, 'medium', 'textPlaceholder'),
    flex: 1,
    marginLeft: spacing[4],
  },
  listBottomSpacer: {
    height: 64,
  },
  mapSwitchButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    bottom: spacing[16],
    flexDirection: 'row',
    gap: spacing[6],
    height: 38,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: spacing[12],
    position: 'absolute',
  },
  mapSwitchText: text(12, 'semibold', 'textSecondary'),
} as const;
