import { colors, text, radius, borderWidth, spacing } from './style-primitives';

export const mapStyles = {
  mapLayer: {
    backgroundColor: '#f6f2eb',
    flex: 1,
  },
  placeMarkerBubble: {
    alignItems: 'center',
    borderColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 32,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    width: 32,
  },
  placeMarkerBubbleDimmed: {
    borderColor: 'rgba(148, 163, 184, 0.45)',
    opacity: 0.5,
    transform: [{ scale: 0.88 }],
  },
  placeMarkerBubbleHighlighted: {
    borderColor: colors.surface,
    borderWidth: borderWidth[2],
    opacity: 1,
    transform: [{ scale: 1.12 }],
  },
  placeMarkerSymbol: {
    height: 20,
    width: 20,
  },
  nativeUserLocationMarker: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: radius.full,
    borderWidth: borderWidth[2],
    height: 38,
    width: 38,
  },
  myLocationButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing[16],
    width: 44,
    zIndex: 16,
  },
  zoomControl: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius[12],
    borderWidth: borderWidth[1],
    overflow: 'hidden',
    position: 'absolute',
    right: spacing[16],
    width: 44,
    zIndex: 16,
  },
  zoomButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  zoomDivider: {
    backgroundColor: colors.border,
    height: borderWidth[1],
    width: '100%',
  },
  mapBottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius[16],
    borderTopRightRadius: radius[16],
    left: 0,
    paddingHorizontal: spacing[16],
    paddingTop: spacing[8],
    position: 'absolute',
    right: 0,
    zIndex: 15,
  },
  mapBottomSheetExpanded: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: spacing[16],
  },
  mapSheetFeedScroll: {
    flex: 1,
  },
  mapSheetFeedContent: {
    paddingBottom: 32,
  },
  mapFloatingAction: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 34,
    justifyContent: 'center',
    minWidth: 124,
    paddingHorizontal: spacing[12],
    position: 'absolute',
    zIndex: 18,
  },
  mapFloatingActionText: text(12, 'semibold', 'textSecondary'),
} as const;
