import { colors, text, tokens, borderWidth, radius, spacing } from './style-primitives';

export const tabssearchStyles = {
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    ...text(14, 'bold', 'textPrimary'),
    marginBottom: spacing[12],
  },
  moreButton: {
    marginBottom: spacing[12],
  },
  moreText: text(11, 'semibold', 'textTertiary'),
  bottomTabs: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: borderWidth.hairline,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 30,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    gap: spacing[2],
    justifyContent: 'center',
  },
  tabLabel: text(11, 'medium', 'textTertiary'),
  tabLabelActive: text(11, 'bold', 'primary'),
  searchRoot: {
    backgroundColor: colors.background,
    flex: 1,
    paddingHorizontal: spacing[16],
  },
  searchHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
  },
  backButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 28,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 36,
    paddingHorizontal: spacing[12],
  },
  searchTextInput: {
    color: colors.textPrimary,
    flex: 1,
    fontFamily: tokens.fonts.sansSerif,
    fontSize: 12,
    fontWeight: tokens.typography.fontWeight.medium,
    height: 36,
    letterSpacing: 0,
    padding: 0,
  },
  searchSection: {
    marginTop: spacing[24],
  },
  searchSectionTitle: {
    ...text(14, 'bold', 'textPrimary'),
    marginBottom: spacing[12],
  },
  keywordWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[8],
  },
  keywordPill: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 32,
    justifyContent: 'center',
    paddingHorizontal: spacing[12],
  },
  hotKeywordPill: {
    backgroundColor: colors.accentOrangeSubtle,
    borderColor: colors.accentOrangeMuted,
  },
  hotKeywordText: text(12, 'semibold', 'primary'),
  suggestionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[10],
    height: 40,
  },
  suggestionText: text(14, 'medium', 'textSecondary'),
  suggestionHighlightText: text(14, 'bold', 'primary'),
  recentSearchPill: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[6],
    height: 32,
    paddingLeft: spacing[12],
    paddingRight: spacing[8],
  },
  recentSearchPillText: text(12, 'semibold', 'textSecondary'),
  recentSearchRemoveButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  imagePlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    justifyContent: 'center',
  },
} as const;
