import { colors, text, radius, borderWidth, spacing } from './style-primitives';

export const topcontrolsStyles = {
  root: {
    backgroundColor: colors.background,
    flex: 1,
    overflow: 'hidden',
  },
  headerBar: {
    backgroundColor: colors.surface,
    paddingBottom: spacing[8],
    zIndex: 20,
  },
  mapArea: {
    flex: 1,
    position: 'relative',
  },
  topControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing[8],
    paddingHorizontal: spacing[16],
  },
  dogSelector: {
    alignItems: 'center',
    backgroundColor: colors.inverse,
    borderRadius: radius.full,
    flexDirection: 'row',
    gap: spacing[4],
    height: 36,
    marginRight: spacing[8],
    paddingLeft: spacing[4],
    paddingRight: spacing[8],
  },
  dogAvatarStack: {
    alignItems: 'center',
    flexDirection: 'row',
    minWidth: 28,
  },
  stackedDogAvatar: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.inverse,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 28,
    width: 28,
  },
  stackedDogAvatarPlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    justifyContent: 'center',
  },
  dogSelectorText: text(12, 'bold', 'onInverse'),
  dogSelectorEmpty: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    flexDirection: 'row',
    gap: spacing[4],
    height: 36,
    marginRight: spacing[8],
    paddingHorizontal: spacing[12],
  },
  dogSelectorAddText: text(12, 'bold', 'primary'),
  searchButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radius.full,
    flex: 1,
    flexDirection: 'row',
    gap: spacing[8],
    height: 36,
    paddingHorizontal: spacing[12],
  },
  searchPlaceholder: text(12, 'medium', 'textPlaceholder'),
  categoryRail: {
    height: 36,
    marginTop: spacing[12],
  },
  categoryRailContent: {
    alignItems: 'center',
    paddingLeft: spacing[16],
    paddingRight: spacing[16],
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: borderWidth[1],
    height: 34,
    justifyContent: 'center',
    marginRight: spacing[8],
    paddingHorizontal: spacing[12],
  },
  categoryChipActive: {
    backgroundColor: colors.inverse,
    borderColor: colors.inverse,
  },
  categoryChipText: text(12, 'semibold', 'textSecondary'),
  categoryChipTextActive: text(12, 'bold', 'onInverse'),
} as const;
