import { styled } from 'styled-components/native';
import { Image } from 'expo-image';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Text } from '@/components/ui/text';

export const Root = styled(SafeAreaView)`flex: 1;
  background-color: ${({ theme }) => theme.colors.semantic.light.background};`;
export const Header = styled.View`height: 64px;
  padding: 0 20px;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;`;
export const Tabs = styled.View`flex-direction: row;
  gap: 12px;
  align-items: center;`;
export const TabTitle = styled(Text)<{ $active: boolean }>`font-size: 24px;
  line-height: 32px;
  color: ${({ theme, $active }) => theme.colors.semantic.light[$active ? 'textPrimary' : 'textDisabled']};`;
export const Rail = styled.ScrollView.attrs({ horizontal: true, showsHorizontalScrollIndicator: false, contentContainerStyle: { paddingHorizontal: 20, gap: 8, alignItems: 'center' } })`flex-grow: 0;
  flex-shrink: 0;
  height: 56px;`;
export const Chip = styled.Pressable<{ $active: boolean }>`height: 40px;
  padding: 0 16px;
  border-radius: 20px;
  border-width: 1px;
  border-color: ${({ theme, $active }) => theme.colors.semantic.light[$active ? 'textPrimary' : 'border']};
  background-color: ${({ theme, $active }) => theme.colors.semantic.light[$active ? 'textPrimary' : 'surface']};
  justify-content: center;`;
export const Summary = styled.View`padding: 12px 20px 16px;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;`;
export const Center = styled.View`flex: 1;
  align-items: center;
  justify-content: center;
  padding: 24px;
  gap: 16px;`;
export const Feedback = styled.Pressable`margin: 0 20px 12px;
  padding: 12px;
  border-radius: 8px;
  background-color: ${({ theme }) => theme.colors.semantic.light.accentOrangeSubtle};`;
export const Bottom = styled.View`min-height: 72px;
  padding: 12px 20px;
  flex-direction: row;
  gap: 8px;
  border-top-width: 1px;
  border-color: ${({ theme }) => theme.colors.semantic.light.border};`;
export const ButtonSlot = styled.View`flex: 1;`;
export const EmptyButtonSlot = styled.View`width: 200px;
  margin-top: 8px;`;
export const Row = styled.View<{ $selecting: boolean;
  $selected: boolean }>`
  flex-direction: row;
  align-items: center;
  gap: 12px;
  min-height: ${({ $selecting }) => $selecting ? 112 : 88}px;
  padding: ${({ $selecting, theme }) => $selecting ? theme.spacing[12] : 0}px;
  border-width: ${({ $selecting }) => $selecting ? 1.5 : 0}px;
  border-radius: ${({ theme }) => theme.radius[16]}px;
  border-color: ${({ theme, $selected }) => theme.colors.semantic.light[$selected ? 'primary' : 'border']};
`;
export const RowMain = styled.Pressable`flex: 1;
  flex-direction: row;
  align-items: center;
  gap: 12px;`;
export const PlaceInfo = styled.View`flex: 1;
  align-self: stretch;
  gap: 4px;`;
export const Tags = styled.View`flex-direction: row;
  gap: 4px;
  flex-wrap: wrap;`;
export const Tag = styled.View`height: 20px;
  padding: 0 4px;
  justify-content: center;
  border-radius: ${({ theme }) => theme.radius[4]}px;
  background-color: ${({ theme }) => theme.colors.semantic.light.surfaceSubtle};`;
export const Proof = styled.View`flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
  gap: 4px;`;
export const ProofItem = styled.View`flex-direction: row;
  align-items: center;
  height: 20px;
  gap: 2px;`;
export const Rating = styled.View`flex-direction: row;
  align-items: center;
  gap: 2px;`;
/** 24px 원형 체크박스. components/ui/input/checkbox-input의 CheckboxControl과 같은 스펙. */
export const Check = styled.View<{ $selected: boolean }>`width: 24px;
  height: 24px;
  border-radius: ${({ theme }) => theme.radius.full}px;
  border-width: ${({ theme }) => theme.borderWidth[2]}px;
  border-color: ${({ theme, $selected }) => $selected ? theme.colors.semantic.light.primary : theme.colors.primitive.gray[300]};
  background-color: ${({ theme, $selected }) => theme.colors.semantic.light[$selected ? 'primary' : 'surface']};
  align-items: center;
  justify-content: center;`;
export const CourseCard = styled.View`height: 180px;
  border-radius: 12px;
  overflow: hidden;
  background-color: ${({ theme }) => theme.colors.semantic.light.surfaceMuted};`;
export const CourseMain = styled.Pressable`flex: 1;`;
export const Scrim = styled(Image).attrs({ source: require('../assets/course-overlay.svg'), contentFit: 'fill' as const })`
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 108px;
`;
export const CourseInfo = styled.View`position: absolute;
  bottom: 16px;
  left: 12px;
  right: 12px;
  gap: 6px;
  padding-bottom: 34px;`;
export const Badge = styled.View`position: absolute;
  left: 8px;
  top: 8px;
  padding: 4px 6px;
  border-radius: 6px;
  background-color: ${({ theme }) => theme.colors.semantic.light.overlayScrim};`;
export const TripButton = styled.Pressable`position: absolute;
  bottom: 8px;
  right: 8px;
  height: 28px;
  padding: 0 8px;
  border-radius: 8px;
  background-color: ${({ theme }) => theme.colors.semantic.light.surface};
  flex-direction: row;
  align-items: center;
  gap: 4px;`;
